version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: company_profile
    container_name: company_profile-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - company_profile

  db:
    image: mysql:8.0
    container_name: company_profile-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dblaravel
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_USER: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - company_profile

  nginx:
    image: nginx:alpine
    container_name: company_profile-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - company_profile

networks:
  company_profile:
    driver: bridge
